Import numpy and pandas

In [1]:
import numpy as np
import pandas as pd

Create a python dictionary with 3 labels and 3 numbers of your choice.
Call it my_data.

In [2]:
my_data = {'year': 2019, 'month': 10, 'day': 29}
print(my_data)

{'year': 2019, 'month': 10, 'day': 29}


Create a pandas Series from the my_data dictionary, called my_series.
Display it.

In [3]:
my_series = pd.Series(my_data)
print(my_series)

year     2019
month      10
day        29
dtype: int64


Create a 5x5 array of random integers, from 0 to 100 called nums.
Display it.

In [4]:
import numpy as np

nums = np.random.randint(0, 100, (5, 5))
print(nums)

[[54 19 18 13 20]
 [36 93  7 86 53]
 [74 13 22  2 84]
 [86 80 23 40 56]
 [86 39 78 77 10]]


Create a DataFrame from the nums array, called df.
Label the columns: A,B,C,D,E
Label the index: V,W,X,Y,Z
Display the DataFrame.

In [5]:
df = pd.DataFrame(nums, columns=['A', 'B', 'C', 'D', 'E'], index=['V', 'W', 'X', 'Y', 'Z'])
print(df)

    A   B   C   D   E
V  54  19  18  13  20
W  36  93   7  86  53
X  74  13  22   2  84
Y  86  80  23  40  56
Z  86  39  78  77  10


Display columns B and D.

In [16]:
df[['B', 'D']]


B   D
W  93  86
X  13   2
Y  80  40
Z  39  77

Display rows X and Y.

In [7]:
print(df.loc[['X', 'Y']])

    A   B   C   D   E
X  74  13  22   2  84
Y  86  80  23  40  56


Display element YC.

In [8]:
print(df.loc['Y','C'])

23


Display rows X and Y, and columns B and D.

In [9]:
print(df.loc[['X', 'Y'], ['D','B']])


    D   B
X   2  13
Y  40  80


Display the rows where the number in the 'A' column is greater than 50.

In [10]:
print(df[df['A'] > 50])


    A   B   C   D   E
V  54  19  18  13  20
X  74  13  22   2  84
Y  86  80  23  40  56
Z  86  39  78  77  10


In [11]:
print(df)

    A   B   C   D   E
V  54  19  18  13  20
W  36  93   7  86  53
X  74  13  22   2  84
Y  86  80  23  40  56
Z  86  39  78  77  10


Add a new column F, which is column A x column B.
Display the resulting DataFrame.

In [12]:
df['F'] = df['A'] * df['B']
print(df)

    A   B   C   D   E     F
V  54  19  18  13  20  1026
W  36  93   7  86  53  3348
X  74  13  22   2  84   962
Y  86  80  23  40  56  6880
Z  86  39  78  77  10  3354


Permanently drop row V and column F.
Display the resulting DataFrame.

In [13]:
df = df.drop(['V'], axis=0)
df = df.drop(['F'], axis=1)
print(df)

    A   B   C   D   E
W  36  93   7  86  53
X  74  13  22   2  84
Y  86  80  23  40  56
Z  86  39  78  77  10


Save the dataframe in a file called 'data10.csv'

In [14]:
df.to_csv('data10.csv', index=False)

In [15]:
print(pd.read_csv('data10.csv'))

    A   B   C   D   E
0  36  93   7  86  53
1  74  13  22   2  84
2  86  80  23  40  56
3  86  39  78  77  10
